#!/usr/bin/env bash
set -u

############################################################
# Adjust for each check
############################################################

# Name and messages
MY_NAME="file-crlf"
MY_DESC="Scans recursively for files containing CRLF (Windows Line Feeds)."
MY_FINISH_OK="No files with CRLF (Windows Line Feed) found."
MY_FINISH_ERR="Files with CRLF (Windows Line Feed) found."

# Configuration file prefix
MY_CONF_PRE="FILE_CRLF_"

# Custom required binaries
REQUIRED_CUST_BINS="file"

# Binaries required for fixing
REQUIRED_FIX_BINS="dos2unix"

# Enable custom options (cmd arguments)
# that can be parsed to the actual check binary?
ENABLE_CUST_OPS=0

# When not specifying --custom,
# always use this as the default options
# to parse to the check binary.
DEFAULT_CUST_OPS=""

# How to add your check here:
# ---------------------------
# $1   This comes from xargs and represents
#      the current file to work on:
#      xargs sh '${MY_CHECK}' --
#
# __CUSTOM_OPT_PLACEHOLDER__
#      This will be replaced either with custom options
#      or with the default options.
MY_REG="[[:space:]]CRLF[[:space:]].*line"
MY_CHECK="file \"\$1\" | grep --color=always -E \"${MY_REG}\" || true"

# Can this check fix the problems?
ENABLE_FIX=1

MY_FIX_CMD="file \"\$1\" | grep -qE \"${MY_REG}\" && (dos2unix -k -q -s \"\$1\" && echo \"Fixing: \$1\" || echo \"FAILED: \$1\") || true"

# Command to be displayed for --info
MY_INFO="file -v 2>&1 | grep -E '(([0-9]+)(\.))+'"

# Command to be displayed for --info
MY_FIX_INFO="dos2unix --version 2>&1 | grep -E 'dos2unix\s+[.0-9]+'"


############################################################
# Source library
############################################################

. /usr/bin/awesome-ci-lib.sh
