#!/usr/bin/env bash
set -u

############################################################
# Adjust for each check
############################################################

# Name and messages
MY_NAME="file-nullbyte"
MY_DESC="Scans recursively for files containing a null-byte characters (\x00)."
MY_FINISH_OK="No files with null-byte (\x00) characters found."
MY_FINISH_ERR="Files with null-byte (\x00) characters found."

# Configuration file prefix
MY_CONF_PRE="FILE_NULLBYTE_"

# Custom required binaries
REQUIRED_CUST_BINS=""

# Binaries required for fixing
REQUIRED_FIX_BINS=""

# Enable custom options (cmd arguments)
# that can be parsed to the actual check binary?
ENABLE_CUST_OPS=0

# When not specifying --custom,
# always use this as the default options
# to parse to the check binary.
DEFAULT_CUST_OPS=""

# How to add your check here:
# ---------------------------
# $1   This comes from xargs and represents
#      the current file to work on:
#      xargs sh '${MY_CHECK}' --
#
# __CUSTOM_OPT_PLACEHOLDER__
#      This will be replaced either with custom options
#      or with the default options.
MY_REG="\x0"
#MY_CHECK="if cat -n \"\$1\" | sed -n \"/${MY_REG}/p\" | grep -aq \"^[[:space:]]*[0-9]\"; then printf \"\$1:\"; cat -n \"\$1\" | sed -n \"/${MY_REG}/p\" | sed \"s/^[[:space:]]*//g\"; else true; fi"
MY_CHECK="if cat \"\$1\" | sed -n \"/${MY_REG}/p\" | wc -l | grep -q \"^[1-9]\"; then cat \"\$1\" | sed -n \"/${MY_REG}/p\" | sed \"s/^[[:space:]]*//g\" | sed -e \"s|^|\$1:|\"; else true; fi"

# Can this check fix the problems?
ENABLE_FIX=1

#MY_FIX_CMD="grep -aq \"${MY_REG}\" \"\$1\" && (sed -i\"\" \"s/${MY_REG}//g\" \"\$1\" && echo \"Fixing: \$1\" || echo \"FAILED: \$1\") || true"
MY_FIX_CMD="if cat \"\$1\" | sed -n \"/${MY_REG}/p\" | grep -aq \"^[[:space:]]*[0-9]\"; then (sed -i\"\" \"s/${MY_REG}//g\" \"\$1\" && echo \"Fixing: \$1\" || echo \"FAILED: \$1\"); else true; fi"

# Command to be displayed for --info
MY_INFO="file -v 2>&1 | grep -E '(([0-9]+)(\.))+'"

# Command to be displayed for --info
MY_FIX_INFO=""


############################################################
# Source library
############################################################

. /usr/bin/awesome-ci-lib.sh
