#!/usr/bin/env bash
set -u

############################################################
# Adjust for each check
############################################################

# Name and messages
MY_NAME="git-conflicts"
MY_DESC="Scans recursively for files containing git conflicts."
MY_FINISH_OK="No files with git conflicts found."
MY_FINISH_ERR="Found files with git conflicts."

# Configuration file prefix
MY_CONF_PRE="GIT_CONFLICTS_"

# Custom required binaries
REQUIRED_CUST_BINS=""

# Binaries required for fixing
REQUIRED_FIX_BINS=""

# Enable custom options (cmd arguments)
# that can be parsed to the actual check binary?
ENABLE_CUST_OPS=0

# When not specifying --custom,
# always use this as the default options
# to parse to the check binary.
DEFAULT_CUST_OPS=""

# How to add your check here:
# ---------------------------
# $1   This comes from xargs and represents
#      the current file to work on:
#      xargs sh '${MY_CHECK}' --
#
# __CUSTOM_OPT_PLACEHOLDER__
#      This will be replaced either with custom options
#      or with the default options.
MY_REG="^(<<<<<<<|>>>>>>>|=======)"
MY_CHECK="grep --color=always -inHE \"${MY_REG}\" \"\$1\" || true"

# Can this check fix the problems?
ENABLE_FIX=0

# Command to be displayed for --info
MY_INFO="grep -V | grep -E '([0-9]+\.+)+'"


############################################################
# Source library
############################################################

. /usr/bin/awesome-ci-lib.sh
