#!/usr/bin/env bash
set -u

############################################################
# Adjust for each check
############################################################

# Name and messages
MY_NAME="file-trailing-single-newline"
MY_DESC="Scans recursively for files not containing exactly 1 trailing newline."
MY_FINISH_OK="All files have exactly one trailing newline."
MY_FINISH_ERR="Some files do not have exactly one trailing newline."

# Configuration file prefix
MY_CONF_PRE="FILE_TRAILING_SINGLE_NEWLINE_"

# Custom required binaries
REQUIRED_CUST_BINS="aci-trailing-newline"

# Binaries required for fixing
REQUIRED_FIX_BINS=""

# Enable custom options (cmd arguments)
# that can be parsed to the actual check binary?
ENABLE_CUST_OPS=0

# When not specifying --custom,
# always use this as the default options
# to parse to the check binary.
DEFAULT_CUST_OPS=""

# How to add your check here:
# ---------------------------
# $1   This comes from xargs and represents
#      the current file to work on:
#      xargs sh '${MY_CHECK}' --
#
# __CUSTOM_OPT_PLACEHOLDER__
#      This will be replaced either with custom options
#      or with the default options.

MY_CHECK="aci-trailing-newline -1 \"\$1\" || echo \"\$1: Not exactly one trailing newline at EOF.\""

# Can this check fix the problems?
ENABLE_FIX=1

# Command for fixing
MY_FIX_CMD="aci-trailing-newline -1 \"\$1\" || ((echo \"\" >> \"\$1\" && sed -i\"\" -e :a -e \"/^\n*\\\$/{\\\$d;N;ba\" -e \"}\" \"\$1\") && echo \"Fixing: \$1\" || echo \"FAILED: \$1\")"

# Command to be displayed for --info
MY_INFO="aci-trailing-newline -v"


############################################################
# Source library
############################################################

. /usr/bin/awesome-ci-lib.sh
