#!/usr/bin/env bash
set -u

############################################################
# Adjust for each check
############################################################

# Name and messages
MY_NAME="file-cr"
MY_DESC="Scans recursively for files containing CR (Carriage Return only newlines)."
MY_FINISH_OK="No files with CR (Carriage Return only newline) found."
MY_FINISH_ERR="Files with CR (Carriage Return newline) found."

# Configuration file prefix
MY_CONF_PRE="FILE_CR_"

# Custom required binaries
REQUIRED_CUST_BINS="file"

# Binaries required for fixing
REQUIRED_FIX_BINS=""

# Enable custom options (cmd arguments)
# that can be parsed to the actual check binary?
ENABLE_CUST_OPS=0

# When not specifying --custom,
# always use this as the default options
# to parse to the check binary.
DEFAULT_CUST_OPS=""

# How to add your check here:
# ---------------------------
# $1   This comes from xargs and represents
#      the current file to work on:
#      xargs sh '${MY_CHECK}' --
#
# __CUSTOM_OPT_PLACEHOLDER__
#      This will be replaced either with custom options
#      or with the default options.
MY_REG="[[:space:]]CR(,)?[[:space:]].*line"
MY_CHECK="file \"\$1\" | grep --color=always -E \"${MY_REG}\" || true"

# Can this check fix the problems?
ENABLE_FIX=1

MY_FIX_CMD="file \"\$1\" | grep -qE \"${MY_REG}\" && (TERM=vt100 vi -u NONE -n -es -c \"%s/\r/\r/g\" -c \"wq\" \"\$1\" > /dev/tty && echo \"Fixing: \$1\" || echo \"FAILED: \$1\") || true"

# Command to be displayed for --info
MY_INFO="file -v 2>&1 | grep -E '(([0-9]+)(\.))+'"

# Command to be displayed for --info
MY_FIX_INFO=""


############################################################
# Source library
############################################################

. /usr/bin/awesome-ci-lib.sh
